### ISSUE TITLE
ModX Package not working

### ISSUE THREAD

**Issue by ysanmiguel** [Indigo744/Modx-Revo-Simple-Ace-Code-Editor#1]
Hello mate, I tried to download and install the package from ModX repo but is not working, then tried manually but not working again, can you please check it, the package looks good.

Cheers!!!

**Comment by Indigo744** [comment]
Which version of revo are you using?

**Comment by ysanmiguel** [comment]
Exactly, let me know when is ready I really want to try it, the old ACE doesn't have the JS syntax.
Thank you mate!

**Comment by ysanmiguel** [comment]
I use Packman to updates my web sites, it works well but is quite basic, I think do the package manually might be a pain.

**Comment by Indigo744** [comment]
I switched to a new build script and published it to Modx extra.
In the mean time, you can try it to manually upload the file in the `_dist` folder

**Comment by ysanmiguel** [comment]
Ahhh mate this is lot better than ACE, great job my friend, now my CSS is full of errors hahaha
it's not recognizing CSS variables, is there an option to move from CSS to SASS?
and do you think is possible activate the autocomplete? what do you think?

Thank you mate, looks amazing!

**Comment by ysanmiguel** [comment]
Just realise that is not recognising the HTML, CSS and JS works well.

**Comment by Indigo744** [comment]
I may need to have a look into the ACE options to check for SASS.
I'll have a look for the autocomplete as well.

What do you mean by "it is not recognising the HTML"? In which view?

**Comment by Indigo744** [comment]
Can you tell me how you are editing SASS file? Using the file editor or in a chunk or something?
What is the file extension?

**Comment by ysanmiguel** [comment]
Mate is this one, it's excellent: https://modx.com/extras/package/csssweet

and the HTML is not being recognized in normal chunks, I normally edit JS, SCSS and HTML from the manager inside chunks linked to Static Files, JS and CSS are working well but the HTML looks plain, no colors no nothing. Cheers mate!

**Comment by Indigo744** [comment]
Could you try this one: https://github.com/Indigo744/Modx-Revo-Simple-Ace-Code-Editor/raw/master/_dist/simpleacecodeeditor-1.2.0-pl.transport.zip

**Comment by ysanmiguel** [comment]
I tried but still the same, look the images:

SimpleCodeEditor: [https://drive.google.com/open?id=11LA_mtzW44lVhn9KqHjm6l3Iu4viTIGR](url)
CSS: OK but not recognizing SASS or ModX labels
JS: Great but auto-fill still not working
HTML: Not recognizing HTML or ModX labels

ACE: [https://drive.google.com/open?id=1-T9MFxaQ9AfKIXcei-7M58RwVEdpxptU](url)
CSS: recognize SASS and ModX labels, auto-fill not working
JS: Terrible
HTML: recognize HTML and ModX labels, auto-fill not working

**Comment by Indigo744** [comment]
I guess when you say "SimpleCodeEditor", you mean this plugin, and "ACE" is [this one](https://modx.com/extras/package/ace)?

Chunks are HTML, so I set the mode to `text/html` (unless the chunk is set to static, then the file type is checked to get the mode). There is not so much we can do.
You can activate the new option `SettingsMenu` (set to YES). Then you'll be able to open a settings menu using CTRL+Q and you will be able to select a different mode according to your need.

**Comment by ysanmiguel** [comment]
Yes ACE is technically the same or similar that what you are doing.
but it has the JS disable and other things missing, I think a mix between yours and CE will be perfect!
I'll check the settings.

**Comment by Indigo744** [comment]
How would you feel to provide the proper mime type to use in the chunk description or in the chunk code (like a shebang)?

Example in the description: `This is a chunk description (text/x-sass)` 

Example in the code:
```
/**! text/x-sass */
nav {
  ul {
    margin: 0;
    padding: 0;
    list-style: none;
  }

  li { display: inline-block; }

  a {
    display: block;
    padding: 6px 12px;
    text-decoration: none;
  }
}
```

**Comment by Indigo744** [comment]
Anyway, regarding the modx tags (or label as you call it), this is something quite complicated to do. 
I should take some time to look into the ACE plugin code ([see this](https://github.com/danyaPostfactum/modx-ace/blob/master/assets/components/ace/modx.texteditor.js#L491)) to see how they do it, and try to implement it.

However, it would require quite more complexity, which is something I'm not very fond of (this is suppose to be a *simple* plugin...). I'll think about it.

**Comment by ysanmiguel** [comment]
I'll check ACE too and see how can I help you.

**Comment by Indigo744** [comment]
I've linked the relevant code above: https://github.com/danyaPostfactum/modx-ace/blob/master/assets/components/ace/modx.texteditor.js#L491

Still, I will need to extract only the relevant part (the modx highlight part) and put it in a proper file, then add it to the build process.

At the beginning, I wanted only a simple plugin that fit only inside the plugin's code in the DB (no other files needed). Hence why I'm a little reluctant in adding *too* much functionality.

**Comment by Indigo744** [comment]
Anyway, what do you think about the MIME type detection for chunk in 1.3.0?

**Comment by Indigo744** [comment]
Well, after some though I decided it would be definitively a nice thing to have.
I've managed to add the modx highlighting, please check the 1.3.0-pl: https://github.com/Indigo744/Modx-Revo-Simple-Ace-Code-Editor/raw/master/_dist/simpleacecodeeditor-1.3.0-pl.transport.zip

![image](https://user-images.githubusercontent.com/7137528/39629531-d2a83d0c-4fac-11e8-84aa-f85d797c5b5c.png)
![image](https://user-images.githubusercontent.com/7137528/39629556-e658e8d8-4fac-11e8-83a6-4596cd608039.png)

Hope you like it.

**Comment by ysanmiguel** [comment]
Well looks better
I tried the MIME type in the description area for sass but it's not working, what do you think about the auto-fill? I think that will be an excellent implementation.

Well done mate! 👍

**Comment by Indigo744** [comment]
Make sure you have the latest version installed, and perform a full browser refresh (CTRL-F5 or something) to bust any cache related issues.
If you add `text/x-sass` either in the Chunk description or in the first line, it should use this mode.
Note it only works for chunks of course.

**Comment by ysanmiguel** [comment]
Mate you are my hero from now on 👍 
Everything looks very well, just one last question: The MIME detect looks like is not working on my SCSS

check the image: 

![sketch](https://user-images.githubusercontent.com/4923727/39719386-fb226d12-5230-11e8-8a64-38a74b94b945.png)

**Comment by Indigo744** [comment]
Oh right. I didn't know you were using static file.
This is a special case. If a chunk is static, the MIME type is detected by taking the file extension.
So, what it the file extension? Since you blank'd the filename, I cannot see it :smile:

Here is the mapping:
```php
$extensionMap = array(
    'tpl'   => 'text/html',
    'htm'   => 'text/html',
    'html'  => 'text/html',
    'css'   => 'text/css',
    'scss'  => 'text/x-scss',
    'sass'  => 'text/x-sass',
    'less'  => 'text/x-less',
    'svg'   => 'image/svg+xml',
    'xml'   => 'application/xml',
    'xsl'   => 'application/xml',
    'js'    => 'application/javascript',
    'json'  => 'application/json',
    'php'   => 'application/x-php',
    'sql'   => 'text/x-sql',
    'txt'   => 'text/plain',
);
```

**Comment by ysanmiguel** [comment]
well it's .css, but you are right I'll change it and let you know. Thanks!

**Comment by Indigo744** [comment]
`.css` will be recognized as CSS. For SASS, you should use `.sass` or `.scss` extension.
Anyway, [version 1.3.1](https://github.com/Indigo744/Modx-Revo-Simple-Ace-Code-Editor/releases/tag/1.3.1-pl) will let you override the file extension detection as well 😸

**Comment by ysanmiguel** [comment]
Mate, I'm so happy, it works very good on SCSS, JS and HTML. Excellent work my friend, thank you very much!!!

**Comment by Indigo744** [comment]
No problem 😄
I'm closing this thread. Feel free to open a new one if you have any issue.
