### ISSUE TITLE
Question about Properties

### ISSUE THREAD

**Issue by ozmaat** [Indigo744/Modx-Revo-Simple-Ace-Code-Editor#11]
Hi,

Thanks for the great extra. 

I have defined a property set and change the theme from new property set but it is not reflected. If I change it the from default, it works. 

Is it possible to save the editor properties that you open with ctrl + Q. I can change these properties like wrapping or font-size, but each time you open the editor, you have to manually change them again.

**Comment by Indigo744** [comment]
Hello,

If I recall correctly how modx Revo handle Property Sets, you also need to apply the new Property Set to each of the plugin's events (should be in events tab, last column). It's not that obvious, I know.

As for your second request, I will try to have a look into persistent options.

**Comment by Indigo744** [comment]
Depending on the setting, I may be able to offer you the ability to set it through Plugin Properties.

**Comment by ozmaat** [comment]
Thanks for the feedback.  Having soft wrap and font size settings would be great.

**Comment by Indigo744** [comment]
@ozmaat could you try the latest [1.5.0-beta3](https://github.com/Indigo744/Modx-Revo-Simple-Ace-Code-Editor/releases/tag/1.5.0-beta3) and tell me if everything is good for you?

I added `SoftWraps`, `FontSize` and `SoftTabs` properties.

**Comment by ozmaat** [comment]
@Indigo744. Sorry for the late response. I have installed and all is okay. Thanks a lot for the changes.
