### ISSUE TITLE
Jumping text positions when editing in non-fullscreen mode

### ISSUE THREAD

**Issue by mindeffects** [Indigo744/Modx-Revo-Simple-Ace-Code-Editor#14]
The lines jump to the cursor position in column 1 when code is edited in non-fullscreen mode.

![ace-error](https://user-images.githubusercontent.com/458619/48143568-56e80300-e2af-11e8-915c-f580e23866af.gif)

After going fullscreen and back again (the short white blank in the anim-gif), everything works as expected.
The solution to switch to another style template does not work.

**Comment by Indigo744** [comment]
I cannot reproduce it...

What are you editing? What are your plugin's configuration?

**Comment by Indigo744** [comment]
Alright, I was able to reproduce it with `text/html` on a TV.
I'll investigate.

**Comment by Indigo744** [comment]
First workaround: set parameter `SoftWraps` to a value different than `off` (like `free`)

**Comment by Indigo744** [comment]
Workaround (for the meantime): set `SoftWraps` to `printMargin`

**Comment by Indigo744** [comment]
Can you check the latest [1.5.2 release](https://github.com/Indigo744/Modx-Revo-Simple-Ace-Code-Editor/releases/tag/1.5.2-pl)?

**Comment by mindeffects** [comment]
Nice job! With 1.5.2 the jumping lines are gone.
Thanks!!!
