### ISSUE TITLE
Themes not staying anymore.

### ISSUE THREAD

**Issue by thewhiterabbit** [Indigo744/Modx-Revo-Simple-Ace-Code-Editor#17]
After updating MODX I can't get the theme to stay as I select it. I changed theme in the properties after unlocking, then saving the properties.

I'm using MODX 2.7.

Edit/Update:
TinymceWrapper was hijacking the plugin.

Conclusion:
You can only use one or the other, both plugins will not work together because Simple Ace Code Editor gets overridden by TinymceWrapper (because it also uses Ace).

**Comment by Indigo744** [comment]
Hello,

> Edit/Update:
> TinymceWrapper was hijacking the plugin.

Does this mean the issue is resolved? If yes, please close the ticket :smile:

Thanks.

**Comment by thewhiterabbit** [comment]
Oops, got in a hurry yesterday. Yes, it's resolved. Sorry about that.

**Comment by Indigo744** [comment]
No problem. Glad you figured it out 😉
