### ISSUE TITLE
Lacking in almost every way

### ISSUE THREAD

**Issue by itsmerobliberty** [Indigo744/Modx-Revo-Simple-Ace-Code-Editor#2]
Fully installed and enabled but missing almost everything the old Ace extra had. You mention a list of properties that can be enabled (Auto-complete, Emmet, whatever you think CTRL-D does) but the only 2 properties available are AcePath and AceTheme... and even AcePath is using an OLD version of ACE, what's the deal?

I was excited to finally get an updated ACE with support for 4+ year old CSS properties *cough* Flex *cough* but this extra really under delivered. 

Am I missing something obvious? Did I miss a checkbox somewhere? Please help me understand why this exists.

**Comment by itsmerobliberty** [comment]
I appreciate that there is a 1.3.0 coming and I appreciate the work you've done.  I would never install a manual extra from Github without MODX review. That's terrible practice.

I suggest including the "This version is deprecated. It is recommended to use a newer version." note on your Github description too. Not everyone visits that [extra page](https://modx.com/extras/package/simpleacecodeeditor), since most download directly from the repository and there is no direct link.

You have to understand the disappointment of seeing updates, and promises, to extra that's been missing meaningful updates for over 4 years and then to install it and find it's even worse off then it's predecessor. Maybe I hastily wrote my "review" out of pure disappointment, but 1.0.0 should never have been released.

I _am_ working on some extras and I welcome your critique when they are released.

**Comment by itsmerobliberty** [comment]
I prefer Emmet over Auto-Complete, at least in CSS. I thought the old Ace worked ok for my needs in JS, but I’ll keep my eye on it.

A note on Emmet with this build, it’s mention  that the ext-Emmet will need to be loaded alongside ace.js but without official documentation on how to do so. There appears to be some form of Emmet working out of the box, but it’s not the full featured 1.3.3 version with support for Grid and Flexbox. We also encounter a cross-origin error with out of the Emmet. Thoughts?

**Comment by Indigo744** [comment]
@itsmerobliberty if you didn't update the `AcePath` property, which points to CDNJS, then it will automatically find all needed files in CDNJS as well.

Can you show me the cross-origin error?

**Comment by Indigo744** [comment]
@itsmerobliberty if I update the help string to `Note that "ext-emmet.js" must be available alongside ace.js (will be retrieve from <AcePath>/ext-emmet.js)`, does it become clearer? Does it helps?

**Comment by Indigo744** [comment]
Emmet feature is indeed broken ☹️  I will release an update soon.

**Comment by Indigo744** [comment]
A new release 1.4.0 is available: https://github.com/Indigo744/Modx-Revo-Simple-Ace-Code-Editor/releases/tag/1.4.0-pl

**Comment by Indigo744** [comment]
Modx extra is still in 1.1.0-pl 😦 but if you want there is a [1.4.3 available](https://github.com/Indigo744/Modx-Revo-Simple-Ace-Code-Editor/releases/tag/1.4.3-pl).

**Comment by itsmerobliberty** [comment]
Thanks! Great progress.

**Comment by Indigo744** [comment]
Note that 1.2.0 is, at last, [available in modx repo](https://modx.com/extras/package/simpleacecodeeditor). As well as 1.4.3. 😸
