### ISSUE TITLE
Emmet Integration

### ISSUE THREAD

**Issue by c0mat0se** [Indigo744/Modx-Revo-Simple-Ace-Code-Editor#3]
Hi there,

Awesome extra,

I am trying to integrate Emmet, as you list that I have to include the emmet alongside ace.js.  After looking at the code (I am no expert in php) it looks like ace.js is being pulled in via a CDN, so where would you recommend I put the emment file?

Thanks for the updated ACE, the other one is a little ancient :)

**Comment by Indigo744** [comment]
The plugin uses the `AcePath` property to get the js files.
By default, everything is loaded through CDNJS. Hence if you set the `Emmet` property to `YES`, then it should include it automatically.

Note that you will need at least [version 1.2.0](https://github.com/Indigo744/Modx-Revo-Simple-Ace-Code-Editor/releases).  The Modx repository is still at version 1.1.0 and awaits validation.

**Comment by c0mat0se** [comment]
Hmm interesting. It seems as though the plugin call (since emmet does not actually show anything) gets blocked. Could be an .htaccess thing or something.  Thanks for your help regardless!

**Comment by Indigo744** [comment]
I'll look into it and get back to you

**Comment by Indigo744** [comment]
Emmet is indeed not working. I'll release an update soon to fix the issue!

**Comment by Indigo744** [comment]
Can you please try the new release 1.4.0: https://github.com/Indigo744/Modx-Revo-Simple-Ace-Code-Editor/releases/tag/1.4.0-pl

You will need to install it manually.

**Comment by c0mat0se** [comment]
Wow! You're fast! It seems as though emmet is working perfectly now!

**Comment by ysanmiguel** [comment]
Mate. I installed the 1.4.0 but the highlight for scss and JS are missing, and it's not showing the html code in the chunks.
The 1.3.0 was working well for me, any ideas?

**Comment by c0mat0se** [comment]
Did you completely uninstall and remove the previous 1.3.1? I had a conflicting issue, and solved it by starting completely fresh with 1.4.0. Although I do get a few syntax errors for the closing `</head>` and opening `<body>` tags, everything else is syntax highlighting for SCSS.

**Comment by Indigo744** [comment]
@ysanmiguel you can try as @c0mat0se said, and also you should force a refresh and clear your browser cache ([see how](https://en.wikipedia.org/wiki/Wikipedia:Bypass_your_cache)).

**Comment by Indigo744** [comment]
Now that I think of it, maybe I should implement a cache buster? I'll look into it.

**Comment by Indigo744** [comment]
Can you open a new issue and provide a screenshot of the chunk which has this issue? Thanks.

**Comment by Indigo744** [comment]
@c0mat0se everything is ok then? If so, feel free to close this issue!

**Comment by ysanmiguel** [comment]
One last question, I activated emmet but not sure how to use it, I'm trying: 
`div>ul>li`
then press enter and nothing happen, any quick guide please?

**Comment by Indigo744** [comment]
You should press TAB to expand an emmet abbreviation.
Maybe I should add this to the doc...

**Comment by Indigo744** [comment]
Well actually, it seems to be the[ standard for Emmet](https://docs.emmet.io/actions/expand-abbreviation/):

> In some editors (Eclipse, Sublime Text 2, CodeMirror) “Expand Abbreviation” can be invoked with Tab key.

**Comment by ysanmiguel** [comment]
The tab key is not working for me, have you try it?
or may be is because I had the autocomplete(live) and is crashing with the emmet tab?

**Comment by Indigo744** [comment]
I published [a new 1.4.2 version](https://github.com/Indigo744/Modx-Revo-Simple-Ace-Code-Editor/releases/tag/1.4.2-pl) which should take care of cache issue.

**Comment by ysanmiguel** [comment]
OK mate, done, it was the extension on the Static File, I just put .html and it works.
I think you should put that in the documentation too.
Cheers! 👍

**Comment by Indigo744** [comment]
It is explained in the doc 😸  https://github.com/Indigo744/Modx-Revo-Simple-Ace-Code-Editor/blob/master/readme.md#mime-detection

**Comment by ysanmiguel** [comment]
👍 excellent
