### ISSUE TITLE
Icon missing

### ISSUE THREAD

**Issue by ysanmiguel** [Indigo744/Modx-Revo-Simple-Ace-Code-Editor#4]
Hello mate, based on the 1.3.1 release, the icon on the top corner to make the code are full screen is missing.
Thanks mate.

**Comment by Indigo744** [comment]
I don't understand. Can you show me a screenshot?

**Comment by ysanmiguel** [comment]
Here is:

![sketch](https://user-images.githubusercontent.com/4923727/39776950-230bcbe2-52fa-11e8-89bd-ee8c7f7695fb.png)

**Comment by Indigo744** [comment]
Did this icon exists before? Never seen it 😆 I'll look into Ace doc

**Comment by Indigo744** [comment]
If I add the feature through the F11 key, would it be ok?
I don't want to spend time adding an icon and whatnot 😅

**Comment by Indigo744** [comment]
Check latest version: https://github.com/Indigo744/Modx-Revo-Simple-Ace-Code-Editor/releases/tag/1.4.1-pl

**Comment by ysanmiguel** [comment]
Mate this version is working very good, the fullscreen (F11) works perfect, excellent work my friend, thanks a lot.
One last question, I activated emmet but not sure how to use it, I'm trying: `#page>div.logo+ul#navigation>li*5>a{Item $}`

inside a chunk but is not converting that into a ul list.
