### ISSUE TITLE
Full Screen Search box problem

### ISSUE THREAD

**Issue by ysanmiguel** [Indigo744/Modx-Revo-Simple-Ace-Code-Editor#5]
Hello mate is me again, just to tell you there is a tiny problem with the search box on Fullscreen, it appear behind the manager buttons but it can be fixed easilly with a zindex:12 in the CSS file. See the picture.

Something else might be good is disabling the printing line that appear in the middle of the screen, it's quite annoying don't you think?.

Cheers mate.

![sketch](https://user-images.githubusercontent.com/4923727/39815031-b45b50f6-538e-11e8-99b0-0003c589ea60.png)

**Comment by Indigo744** [comment]
See new release: https://github.com/Indigo744/Modx-Revo-Simple-Ace-Code-Editor/releases/tag/1.4.3-pl

Note that I couldn't specify a z-index as the whole editor should remain under the save menu for it to be visible. Hence the solution was to put the searchbox on the bottom when in fullscreen.

**Comment by ysanmiguel** [comment]
Great mate, well done! 👍
