### ISSUE TITLE
Syntax Highlighting Issues?

### ISSUE THREAD

**Issue by c0mat0se** [Indigo744/Modx-Revo-Simple-Ace-Code-Editor#6]
I have some interesting discrepancies in the highlighting in MODX vs the Ace Editor highlight demo. 

For instance, using the flex property for CSS: `justify-content: center;` in MODX it does not syntax highlight for `justify-content`, although in the Ace Editor demo seen here: (https://ace.c9.io/build/kitchen-sink.html) it highlights perfectly. 

Could this be something to do with the custom MODX highlighting in `modx_highlight_rules.js`? It happens with the old Ace extra as well, and it seems the only similarities are that file pulled from that project.

**Comment by Indigo744** [comment]
Indeed, I can reproduce it with `justify-content: center;`. I'll look into it asap :smile:

**Comment by Indigo744** [comment]
Well, actually it _does_ work:

**in CSS:**

![image](https://user-images.githubusercontent.com/7137528/39859977-f0481772-543b-11e8-8ddf-84b8e69a0d9d.png)

**in HTML:**

![image](https://user-images.githubusercontent.com/7137528/39860030-1d4eda30-543c-11e8-8e64-9af1e7211201.png)

**However, it doesn't work in SASS**:
![image](https://user-images.githubusercontent.com/7137528/39860076-520c4c44-543c-11e8-8794-fec20274f404.png)

Which is the same as Ace (try in the kitchen sink)

**Comment by Indigo744** [comment]
The `flex-flow` property suffers from the same issue.

**Comment by Indigo744** [comment]
@c0mat0se I think the proper step would be to open a ticket in the Ace repo https://github.com/ajaxorg/ace/issues regarding SASS highlighting issues.

**Comment by c0mat0se** [comment]
Will do. Thanks man!
