### ISSUE TITLE
Setting the Theme

### ISSUE THREAD

**Issue by thewhiterabbit** [Indigo744/Modx-Revo-Simple-Ace-Code-Editor#9]
Hello,

I'm trying to locate the setting for the theme in your Ace plugin for modx.

Where is it?

**Comment by Indigo744** [comment]
Hi,

It is located in the plugin's properties.
When editing a plugin, there is a tab "Properties" at the right (after "System Events").

There, you should create a new Property Set, which will allow you to override the default properties.

The `Theme` parameter is the last one on the list.

**Comment by thewhiterabbit** [comment]
Thank you very much for that information!
